apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-gitops-repo
spec:
  workspaces:
    - name: source
  params:
    - name: gitops-repo-url
      type: string
    - name: image-tag
      type: string
  steps:
    - name: git-update
      image: alpine/git:v2.36.2
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        git clone $(params.gitops-repo-url) gitops-repo
        cd gitops-repo
        
        sed -i 's|image: .*|image: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/my-app:$(params.image-tag)|g' deployment.yaml
        
        git config user.email "pipeline@openshift.com"
        git config user.name "OpenShift Pipeline"
        
        git add deployment.yaml
        git commit -m "Update image tag to $(params.image-tag)"
        git push origin main